import type { RouteRecordRaw } from 'vue-router';

/** Redirect legacy unprefixed / payroll-prefixed URLs to owning-module routes. */
export const legacyRouteRedirects: RouteRecordRaw[] = [
  { path: '/timesheet', redirect: '/payroll/timesheet' },
  { path: '/scheduler', redirect: '/payroll/scheduler' },
  { path: '/calendars', redirect: '/payroll/scheduler' },
  { path: '/hr/employees/vacancies', redirect: '/hr/vacancies' },
  { path: '/hr/employees/candidates', redirect: '/hr/candidates' },
  { path: '/payroll/employees/vacancies', redirect: '/hr/vacancies' },
  { path: '/payroll/employees/candidates', redirect: '/hr/candidates' },
  {
    path: '/employees/:pathMatch(.*)*',
    redirect: (to) => `/hr/employees/${String(to.params.pathMatch ?? '')}`,
  },
  {
    path: '/employee/:id',
    redirect: (to) => `/hr/employees/${String(to.params.id)}`,
  },
  { path: '/leaves', redirect: '/payroll/leaves/list' },
  {
    path: '/leaves/:pathMatch(.*)*',
    redirect: (to) => `/payroll/leaves/${String(to.params.pathMatch ?? '')}`,
  },
  { path: '/reports', redirect: '/payroll/reports/journal-entries' },
  {
    path: '/reports/:reportId',
    redirect: (to) => `/payroll/reports/${String(to.params.reportId)}`,
  },
  { path: '/core/reports', redirect: '/payroll/reports/journal-entries' },
  {
    path: '/core/reports/:reportId',
    redirect: (to) => `/payroll/reports/${String(to.params.reportId)}`,
  },
  { path: '/settings', redirect: '/payroll/settings' },
  {
    path: '/settings/:pathMatch(.*)*',
    redirect: (to) => `/payroll/settings/${String(to.params.pathMatch ?? '')}`,
  },
  { path: '/payroll/settings/pipelines', redirect: '/admin/settings/pipelines' },
  { path: '/payroll/settings/modules', redirect: '/admin/settings/modules' },
  { path: '/payroll/settings/database-backup', redirect: '/admin/settings/database-backup' },
  { path: '/payroll/settings/file-storage', redirect: '/admin/settings/file-storage' },
  { path: '/payroll/settings/email', redirect: '/admin/settings/email' },
  { path: '/payroll/settings/login-page', redirect: '/admin/settings/login-page' },
  { path: '/payroll/settings/menu', redirect: '/admin/settings/menu' },
  { path: '/payroll/settings/roles', redirect: '/admin/settings/roles' },
  { path: '/payroll/settings/organization', redirect: '/admin/settings/organization' },
  { path: '/payroll/settings/users', redirect: '/admin/settings/users' },
  { path: '/payroll/settings/vacancy-stages', redirect: '/hr/settings/vacancy-stages' },
  { path: '/payroll/settings/candidate-stages', redirect: '/hr/settings/candidate-stages' },
  { path: '/payroll/settings/general/vacancy-stages', redirect: '/hr/settings/vacancy-stages' },
  { path: '/payroll/settings/general/candidate-stages', redirect: '/hr/settings/candidate-stages' },
  { path: '/payroll/settings/job-titles', redirect: '/hr/settings/job-titles' },
  { path: '/payroll/settings/department', redirect: '/hr/settings/department' },
  { path: '/payroll/settings/worksite', redirect: '/hr/settings/worksite' },
  { path: '/payroll/settings/holidays', redirect: '/hr/settings/holidays' },
  { path: '/payroll/settings/relationship', redirect: '/hr/settings/relationship' },
  { path: '/payroll/settings/degree', redirect: '/hr/settings/degree' },
  { path: '/payroll/settings/country', redirect: '/hr/settings/country' },
  { path: '/payroll/settings/district', redirect: '/hr/settings/district' },
  { path: '/payroll/settings/locality', redirect: '/hr/settings/locality' },
  { path: '/payroll/settings/institution', redirect: '/hr/settings/institution' },
  { path: '/payroll/settings/general/job-titles', redirect: '/hr/settings/job-titles' },
  { path: '/payroll/settings/general/department', redirect: '/hr/settings/department' },
  { path: '/payroll/settings/general/worksite', redirect: '/hr/settings/worksite' },
  { path: '/payroll/settings/general/holidays', redirect: '/hr/settings/holidays' },
  { path: '/payroll/settings/general/relationship', redirect: '/hr/settings/relationship' },
  { path: '/payroll/settings/general/degree', redirect: '/hr/settings/degree' },
  { path: '/payroll/settings/general/country', redirect: '/hr/settings/country' },
  { path: '/payroll/settings/general/district', redirect: '/hr/settings/district' },
  { path: '/payroll/settings/general/locality', redirect: '/hr/settings/locality' },
  { path: '/payroll/settings/general/institution', redirect: '/hr/settings/institution' },
  { path: '/accounts', redirect: '/payroll/settings/accounts' },
];
